import streamlit as st

def show_references():
    st.header("Références")

    st.write("Abdar, A. K., Sadjadi, S. M., Soltanian-Zadeh, H., Bashirgonbadi, A., & Naghibi, M. (2020, November). Automatic detection of coronavirus (COVID-19) from chest CT images using VGG16-based deep-learning. In 2020 27th National and 5th International Iranian Conference on Biomedical Engineering (ICBME) (pp. 212-216). IEEE.")
    st.write("Abdullah, S. M. S., & Abdulazeez, A. M. (2021). Facial expression recognition based on deep learning convolution neural network: A review. Journal of Soft Computing and Data Mining, 2(1), 53-65.")
    st.write("An, Y., Hu, T., Wang, J., Lyu, J., Banerjee, S., & Ling, S. H. (2019, July). Lung Nodule Classification using A Novel Two-stage Convolutional Neural Networks Structure’. In 2019 41st annual international conference of the IEEE engineering in medicine and biology society (EMBC) (pp. 6259-6262). IEEE.")
    st.write("Aziz, A., Attique, M., Tariq, U., Nam, Y., Nazir, M., Jeong, C. W., ... & Sakr, R. H. (2021). An Ensemble of Optimal Deep Learning Features for Brain Tumor Classification. Computers, Materials & Continua, 69(2).")
    st.write("Campers, H. (2022). Automatisation de la reconnaissance d'espèces animales dans des vidéos de pièges photographiques installés dans les forêts tropicales en Afrique centrale, grâce à l'apprentissage profond.")
    st.write("Darapaneni, N., Subramaniyan, M., Mariam, A., Venkateshwaran, S., Ravi, N., Paduri, A. R., & Gunasekaran, S. (2020, November). Handwritten form recognition using artificial neural network. In 2020 IEEE 15th International Conference on Industrial and Information Systems (ICIIS) (pp. 420-424). IEEE.")
    st.write("Ebenezer, A. S., Kanmani, S. D., Sivakumar, M., & Priya, S. J. (2022). Effect of image transformation on EfficientNet model for COVID-19 CT image classification. Materials Today: Proceedings, 51, 2512-2519.")
    st.write("Géron, A. (2020). Deep Learning avec Keras et TensorFlow: Mise en œuvre et cas concrets. Dunod.")
    st.write("He, K., Zhang, X., Ren, S., & Sun, J. (2016). Deep residual learning for image recognition. In Proceedings of the IEEE conference on computer vision and pattern recognition (pp. 770-778).")
    st.write("Islam, M. R., & Matin, A. (2020, December). Detection of COVID 19 from CT image by the novel LeNet-5 CNN architecture. In 2020 23rd International Conference on Computer and Information Technology (ICCIT) (pp. 1-5). IEEE.")
    st.write("Jaiswal, A., Gianchandani, N., Singh, D., Kumar, V., & Kaur, M. (2021). Classification of the COVID-19 infected patients using DenseNet201 based deep transfer learning. Journal of Biomolecular Structure and Dynamics, 39(15), 5682-5689.")
    st.write("Kanne, J. P., Bai, H., Bernheim, A., Chung, M., Haramati, L. B., Kallmes, D. F., ... & Sverzellati, N. (2021). COVID-19 imaging: what we know now and what remains unknown. Radiology, 299(3), E262-E279.")
    st.write("Kavi B. Obaid, Subhi R. M. Zeebaree & Omar M. Ahmed (2020). Deep Learning Models Based on Image Classification: A Review. International Journal of Science and Business, 4(11), 75-81. DOI: 10.5281/zenodo.4108433")
    st.write("Kaiming He et al. (2016). Deep Residual Learning for Image Recognition, DOI:10.1109/CVPR.2016.90")
    st.write("Lagunas, M., & Garces, E. (2018). Transfer learning for illustration classification. arXiv preprint arXiv:1806.02682.")
    st.write("Landete, P., Loaiza, C. A. Q., Aldave-Orzaiz, B., Muñiz, S. H., Maldonado, A., Zamora, E., ... & Couñago, F. (2020). Clinical features and radiological manifestations of COVID-19 disease. World Journal of Radiology, 12(11), 247.")
    st.write("LeCun Y., Bengio Y., and Hinton G. Deep learning, Nature, vol. 521, no. 7553, pp. 436–444, May 2015, DOI: 10.1038/nature14539.")
    st.write("Liew, S. S., Hani, M. K., Radzi, S. A., & Bakhteri, R. (2016). Gender classification: a convolutional neural network approach. Turkish Journal of Electrical Engineering and Computer Sciences, 24(3), 1248-1264.")
    st.write("Marques, G., Agarwal, D., & De la Torre Díez, I. (2020). Automated medical diagnosis of COVID-19 through EfficientNet convolutional neural network. Applied soft computing, 96, 106691.")
    st.write("O’Malley, Tom and Bursztein, Elie and Long, James and Chollet, François and Jin, Haifeng and Invenrnizzi, Luca and others (2019). https://github.com/keras-team/keras-tuner")
    st.write("Tan, M., & Le, Q. (2019, May). Efficientnet: Rethinking model scaling for convolutional neural networks. In International conference on machine learning (pp. 6105-6114). PMLR.")
    st.write("Villain E. Utilisation de l’intelligence artificielle pour l’aide au diagnostic des patients atteints de pathologies neuro dégénératives. (2021). Imagerie. Université Paul Sabatier - Toulouse III. Français.")
    st.write("Wang, Q., Shen, F., Shen, L., Huang, J., & Sheng, W. (2019). Lung nodule detection in CT images using a raw patch-based convolutional neural network. Journal of digital imaging, 32, 971-979.")
    st.write("Wenchao Cui , Qiong Lu , Asif Moin Qureshi , Wei Li & Kehe Wu (2020): An adaptive LeNet-5 model for anomaly detection, Information Security Journal: A Global Perspective, DOI: 10.1080/19393555.2020.1797248")